version: '3'

services:
    database:
        image: mysql:latest
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=rootPassword
            - MYSQL_DATABASE=prototype-graphql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=userPassword
        ports: 
            - 8006:3306
        volumes:
            - mysql_data:/var/lib/mysql

volumes: 
    mysql_data: {} 
